// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv8-dyNX4MxYoVYX_5TD0AMtNMAydZ2vA',
    appId: '1:689946122229:web:11d96148b10818526372bc',
    messagingSenderId: '689946122229',
    projectId: 'helping-hand-8d28e',
    authDomain: 'helping-hand-8d28e.firebaseapp.com',
    storageBucket: 'helping-hand-8d28e.firebasestorage.app',
    measurementId: 'G-ZK7YNDKZ0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVEsFfk6GlgHTYPhMPrQ6MeXbDfv_qmAg',
    appId: '1:689946122229:android:3d412775ef9e4f4d6372bc',
    messagingSenderId: '689946122229',
    projectId: 'helping-hand-8d28e',
    storageBucket: 'helping-hand-8d28e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA29Qpq8DRz67hgr9IkqfMNHO5xmgsR738',
    appId: '1:689946122229:ios:b85335a11d82ba586372bc',
    messagingSenderId: '689946122229',
    projectId: 'helping-hand-8d28e',
    storageBucket: 'helping-hand-8d28e.firebasestorage.app',
    iosBundleId: 'com.example.helpingHand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA29Qpq8DRz67hgr9IkqfMNHO5xmgsR738',
    appId: '1:689946122229:ios:b85335a11d82ba586372bc',
    messagingSenderId: '689946122229',
    projectId: 'helping-hand-8d28e',
    storageBucket: 'helping-hand-8d28e.firebasestorage.app',
    iosBundleId: 'com.example.helpingHand',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv8-dyNX4MxYoVYX_5TD0AMtNMAydZ2vA',
    appId: '1:689946122229:web:164b01072c601a546372bc',
    messagingSenderId: '689946122229',
    projectId: 'helping-hand-8d28e',
    authDomain: 'helping-hand-8d28e.firebaseapp.com',
    storageBucket: 'helping-hand-8d28e.firebasestorage.app',
    measurementId: 'G-RD9MHP2L8D',
  );
}
